---
title: "ADCP Bathymetric Map Generator"
author: "Michael Kricheldorf"
date: "2023-07-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(marmap)
library(ggplot2)
library(leaflet)
#library(rgdal)
library(sf)
library(raster)
library(dplyr)
library(shiny)
library(sp)

#library(terra)
```

## R Markdown

Tidy data
```{r}
# the sample data collected on June 14, 2023, consolidated and processed through WinRiverII and VMT
jun14_vmt <- read.delim("FCR_14JUN2023_Bathymetric_UTM_original.csv", header=TRUE, sep=",")

# the (mostly) complete reservoir profile from July 6, 2023
jul6_vmt <- read.delim("FCR_6JUL2023_Bathymetric_UTM_original.csv", header=TRUE, sep=",")

adcpdata <- rbind(jun14_vmt, jul6_vmt)

# selects data in order of long (easting), lat (northing), and depth (elev)
adcpdata <- dplyr::select(adcpdata, Easting_WGS84_m, Northing_WGS84_m, Elev_m)

# rename these horrendous column headers
colnames(adcpdata) <- c("long", "lat", "depth")

# filter out outlier depths, remove any duplicate coordinates, and group by (long, lat)
adcpdata %>% 
  group_by(long, lat) %>%  
  unique() %>% #Filter out non-unique values.
  filter(depth < 0, depth > -11) #Remove outlier depths.

```


```{r}

# read in data
adcpdata <- read_csv("/Users/MaryLofton/RProjects/multi-model-chla-prediction/data/data_processed/FCR_bathymetry_2023.csv")
adcpdata <- adcpdata[,-1]

# read in old data
old_fcr <- read_csv("/Users/MaryLofton/RProjects/multi-model-chla-prediction/data/data_processed/FCR_2012_WGS84_UTM_ShapefileExport.csv")
old_fcr <- old_fcr[,-1]

# convert coordinates from WGS84 UTM Zone 17 to WGS84 long/lat

wgs84 = "+init=epsg:4326"
bng = '+proj=utm +zone=17 +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +datum=WGS84 +units=m +no_defs'
bng = '+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 
+ellps=airy +datum=OSGB36 +units=m +no_defs'
bng = "+proj=utm +zone=17 +datum=WGS84 +units=m"

easting <- old_fcr$Easting
northing <- old_fcr$Northing

ConvertCoordinates <- function(easting,northing) {
out = cbind(easting,northing)
mask = !is.na(easting)
sp <-  sp::spTransform(sp::SpatialPoints(list(easting[mask],northing[mask]),proj4string=sp::CRS(bng)),sp::CRS(wgs84))
out[mask,]=sp@coords
out
}

check <- ConvertCoordinates(old_fcr$Easting, old_fcr$Northing)

old_fcr$lat <- check[,2]
old_fcr$long <- check$easting

# extract UTM coordinates
adcpdata_coords <- adcpdata[c("long", "lat")]

# assign the coordinates to UTM, WGS84, and zone 17, measured in units of meters
adcpdata_coords_utm <- SpatialPoints(adcpdata_coords, proj4string=CRS("+proj=utm +zone=17 +datum=WGS84 +units=m"))
# convert the coordinates to Long/Lat in WGS84
adcpdata_coords_geo <- spTransform(adcpdata_coords_utm, CRS("+proj=longlat +datum=WGS84"))

old_coords_geo <- spTransform(old_fcr, CRS("+proj=longlat +datum=WGS84"))

# re-insert converted coordinates
adcpdata_coords <- coordinates(adcpdata_coords_geo)
adcpdata_coords <- as.data.frame(adcpdata_coords)
colnames(adcpdata_coords) <- c("long","lat")
adcpdata$long <- adcpdata_coords$long
adcpdata$lat <- adcpdata_coords$lat


```

```{r}
reg <- griddify(adcpdata, nlon = 150, nlat = 300) #nlon and nlat set the number of pixels in the map; play around with these values. 
class(reg) #Returns the class of data

bat <- as.bathy(reg) #Classifies the data as "bathy"
class(bat) #Returns the class of data

b <- as.raster(bat)
pal <- colorNumeric(c("#0C2C84", "#41B6C4", "#FFFFCC"), 
                    domain = adcpdata$depth,
                    na.color = "transparent")
depth <- unique(adcpdata$depth)

map <- leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(-79.8375,37.3058, zoom = 16) %>% 
  addRasterImage(b, colors = pal) %>% 
  addLegend("bottomright", pal = pal, values = depth, title = "Depth (m)")
map

shinyApp(
  ui = fluidPage(leafletOutput('myMap', height = 800)),
  server = function(input, output) {
    map = leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(-79.8375,37.3058, zoom = 16) %>% 
  addRasterImage(b, colors = pal) %>% 
  addLegend("bottomright", pal = pal, values = depth, title = "Depth (m)")
    output$myMap = renderLeaflet(map)
  }
)

min(adcpdata$depth)

```

